import type { CandidateReportDto } from '../candidates/candidates.dto';
import { renderCandidateReportSections } from './pdf-candidate-sections';
import {
  COLORS,
  DISTRIBUTION_META,
  MARGIN,
  PAGE_HEIGHT,
  PAGE_WIDTH,
  SPACING,
  TYPE,
  sanitizePdfText,
  type CandidatePdfMetadata,
  type PdfDocumentBuilderOptions,
  type RolePdfStats,
} from './pdf-layout.constants';
import { PdfPageRenderer } from './pdf-page-renderer';

export type {
  CandidatePdfMetadata,
  PdfDocumentBuilderOptions,
  RolePdfStats,
} from './pdf-layout.constants';

export class PdfDocumentBuilder extends PdfPageRenderer {
  private constructor(options: PdfDocumentBuilderOptions) {
    super(options);
  }

  static async create(
    options: PdfDocumentBuilderOptions,
  ): Promise<PdfDocumentBuilder> {
    const builder = new PdfDocumentBuilder(options);
    await builder.init();

    return builder;
  }

  addCoverHeader(
    title: string,
    generatedAt: string,
    options?: { candidatesScreened?: number },
  ): void {
    this.addScoreDisclaimer();
    this.y -= SPACING.block;

    this.drawText(
      'Certalytic Integrity Dossier',
      TYPE.preTitle,
      this.boldFont,
      COLORS.primary,
    );
    this.y -= SPACING.block;
    this.drawText(title, TYPE.docTitle, this.boldFont, COLORS.text);
    this.y -= 2;

    if (options?.candidatesScreened !== undefined) {
      this.drawText(
        `Candidates Screened: ${options.candidatesScreened}`,
        TYPE.docMeta,
        this.boldFont,
        COLORS.text,
      );
      this.y -= 2;
    }

    this.drawText(
      `Generated ${generatedAt}`,
      TYPE.docMeta,
      this.regularFont,
      COLORS.muted,
    );
    this.y -= SPACING.block;
    this.drawDivider();
    this.y -= SPACING.block;
  }

  addRoleOverview(
    description: string | null | undefined,
    stats?: RolePdfStats,
  ): void {
    if (stats) {
      if (stats.avgIntegrity !== null) {
        this.drawScoreBox(
          Math.round(stats.avgIntegrity),
          `Avg candidate integrity · ${stats.scored} scored · ${stats.completedCount} completed`,
          this.scoreColor(stats.avgIntegrity),
        );
      } else {
        this.addLabeledBlock('Avg candidate integrity');
        this.addParagraph('No scored candidates yet.');
      }

      for (const item of DISTRIBUTION_META) {
        this.drawDistributionBar(
          item.label,
          stats.distribution[item.key],
          stats.scored,
          item.color,
        );
      }
      this.y -= SPACING.tight;
    }

    if (description?.trim()) {
      this.addLabeledBlock('Job description');
      this.addParagraph(description.trim());
    }
  }

  startCandidatePage(): void {
    this.startNewPage();
    this.candidatePageStarted = true;
  }

  addCandidateReport(
    candidateName: string,
    report: CandidateReportDto,
    metadata?: CandidatePdfMetadata,
  ): void {
    if (!this.candidatePageStarted) {
      this.startCandidatePage();
    }

    this.y -= SPACING.tight;
    this.addIntegrityLevel(report.level);
    this.drawText(
      `Candidate: ${candidateName}`,
      TYPE.section,
      this.boldFont,
      COLORS.text,
    );
    this.y -= SPACING.tight;

    if (metadata?.email) {
      this.drawText(metadata.email, TYPE.docMeta, this.regularFont, COLORS.muted);
      this.y -= SPACING.block;
    } else {
      this.y -= SPACING.subsectionBottom;
    }

    this.addScoreBox(report.score, report.level);
    renderCandidateReportSections(this, report, metadata);

    const followUps = [
      ...report.recommendedActions,
      ...(metadata?.followUpSuggested ?? []),
    ];

    if (followUps.length > 0) {
      this.addSection('Suggested follow-ups');
      this.addBulletList([...new Set(followUps)]);
    }

    this.candidatePageStarted = false;
  }

  addClosingPage(siteUrl: string): void {
    this.startNewPage();

    const contentTop = PAGE_HEIGHT - MARGIN - 120;

    this.page.drawText('Report attestation', {
      x: MARGIN,
      y: contentTop,
      size: TYPE.section,
      font: this.boldFont,
      color: COLORS.text,
    });

    const attestation =
      'This report was generated by Certalytic Candidate Integrity Scoring Engine.';
    this.y = contentTop - 24;
    this.drawWrappedText(attestation, TYPE.subsection, this.boldFont, COLORS.text);

    this.y -= SPACING.block;
    const disclaimer =
      'Certalytic applies automated document parsing, cross-platform verification, interview signal analysis, and statistical consistency modelling to produce integrity indicators. Outputs are advisory assessments intended to support recruiter judgment and should be interpreted alongside live interviews, reference checks, and role-specific validation.';
    this.drawWrappedText(disclaimer, TYPE.body, this.regularFont, COLORS.muted);

    this.drawStamp();

    const footerY = MARGIN + 28;
    this.page.drawLine({
      start: { x: MARGIN, y: footerY + 18 },
      end: { x: PAGE_WIDTH - MARGIN, y: footerY + 18 },
      thickness: 1,
      color: COLORS.border,
    });

    this.page.drawText(sanitizePdfText(siteUrl), {
      x: MARGIN,
      y: footerY,
      size: TYPE.body,
      font: this.regularFont,
      color: COLORS.muted,
    });

    const confidential = 'Confidential hiring intelligence';
    const confidentialWidth = this.regularFont.widthOfTextAtSize(
      confidential,
      TYPE.hint,
    );
    this.page.drawText(confidential, {
      x: PAGE_WIDTH - MARGIN - confidentialWidth,
      y: footerY,
      size: TYPE.hint,
      font: this.regularFont,
      color: COLORS.label,
    });
  }
}
